services:
  server:
    build: .
    image: service-name
    network_mode: host
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  pg:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
